﻿// <auto-generated />
using System;
using LuxotticaSorting.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuxotticaSorting.DataAccess.Migrations
{
    [DbContext(typeof(SortingContext))]
    partial class SortingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LuxotticaSorting.Core.BoxTypes.BoxType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BoxTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoxTypes");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.CarrierCodes.CarrierCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CarrierCodes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarrierCodes");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.ConfirmationBoxes.ConfirmationBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BoxId")
                        .HasColumnType("int");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DivertLane")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConfirmationBoxes");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.Container.ContainerTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContainerTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ContainerTypeId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.ContainerTypes.ContainerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContainerTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContainerTypes");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.DivertLanes.DivertLane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ContainerId")
                        .HasColumnType("int");

                    b.Property<int>("DivertLanes")
                        .HasColumnType("int");

                    b.Property<bool>("Full")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("DivertLanes");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.LogisticAgents.LogisticAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LogisticAgents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogisticAgents");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.Mapping.BoxTypeDivertLane.BoxTypeDivertLaneMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BoxTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DivertLaneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BoxTypeDivertLaneMappings");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.Mapping.CarrierCodeDivertLine.CarrierCodeDivertLaneMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarrierCodeId")
                        .HasColumnType("int");

                    b.Property<int>("DivertLaneId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CarrierCodeId");

                    b.HasIndex("DivertLaneId");

                    b.ToTable("CarrierCodeDivertLaneMappings");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.Mapping.CarrierCodeLogisticAgent.CarrierCodeLogisticAgentMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarrierCodeId")
                        .HasColumnType("int");

                    b.Property<int>("LogisticAgentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarrierCodeLogisticAgentMappings");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.Mapping.DivertLaneZebraConfiguration.DivertLaneZebraConfigurationMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DivertLaneId")
                        .HasColumnType("int");

                    b.Property<int>("ZebraConfigurationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DivertLaneId");

                    b.HasIndex("ZebraConfigurationId");

                    b.ToTable("DivertLaneZebraConfigurationMappings");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.MappingSorter.MappingSorter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BoxTypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarrierCodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContainerTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DivertLaneId")
                        .HasColumnType("int");

                    b.Property<int?>("LogisticAgentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContainerTypeId");

                    b.HasIndex("DivertLaneId");

                    b.HasIndex("LogisticAgentId");

                    b.ToTable("MappingSorters");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.MultiBoxWaves.MultiBoxWave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConfirmationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("DivertLane")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int?>("QtyCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("multiBox_Wave");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.RecirculationLimits.RecirculationLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecirculationLimits");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.ScanLogSortings.ScanLogSorting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BoxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoxType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarrierCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("DivertLane")
                        .HasColumnType("int");

                    b.Property<string>("LogisticAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timestamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrackingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("scanLogSortings");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.WCSRoutingV10.WCSRoutingV10", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BoxId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BoxType")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("CarrierCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ConfirmationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("CurrentTs")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DivertLane")
                        .HasColumnType("int");

                    b.Property<string>("DivertTs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogisticAgent")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("SAPSystem")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("TrackingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("wCSRoutingV10s");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.Zebra.ZebraConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("HostName")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Ip")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NamePrinter")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("PortType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("ZebraConfigurations");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.Zebra.ZebraHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ContainerId")
                        .HasColumnType("int");

                    b.Property<int>("DivertLaneId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ZebraConfigurationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("DivertLaneId");

                    b.HasIndex("ZebraConfigurationId");

                    b.ToTable("ZebraHistorials");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.Container.ContainerTable", b =>
                {
                    b.HasOne("LuxotticaSorting.Core.ContainerTypes.ContainerType", "ContainerType")
                        .WithMany("Containers")
                        .HasForeignKey("ContainerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContainerType");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.DivertLanes.DivertLane", b =>
                {
                    b.HasOne("LuxotticaSorting.Core.Container.ContainerTable", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId");

                    b.Navigation("Container");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.Mapping.CarrierCodeDivertLine.CarrierCodeDivertLaneMapping", b =>
                {
                    b.HasOne("LuxotticaSorting.Core.CarrierCodes.CarrierCode", "CarrierCode")
                        .WithMany()
                        .HasForeignKey("CarrierCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuxotticaSorting.Core.DivertLanes.DivertLane", "DivertLane")
                        .WithMany()
                        .HasForeignKey("DivertLaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarrierCode");

                    b.Navigation("DivertLane");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.Mapping.DivertLaneZebraConfiguration.DivertLaneZebraConfigurationMapping", b =>
                {
                    b.HasOne("LuxotticaSorting.Core.DivertLanes.DivertLane", "DivertLane")
                        .WithMany()
                        .HasForeignKey("DivertLaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuxotticaSorting.Core.Zebra.ZebraConfiguration", "ZebraConfiguration")
                        .WithMany()
                        .HasForeignKey("ZebraConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DivertLane");

                    b.Navigation("ZebraConfiguration");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.MappingSorter.MappingSorter", b =>
                {
                    b.HasOne("LuxotticaSorting.Core.ContainerTypes.ContainerType", "ContainerType")
                        .WithMany()
                        .HasForeignKey("ContainerTypeId");

                    b.HasOne("LuxotticaSorting.Core.DivertLanes.DivertLane", "DivertLane")
                        .WithMany()
                        .HasForeignKey("DivertLaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuxotticaSorting.Core.LogisticAgents.LogisticAgent", "LogisticAgent")
                        .WithMany()
                        .HasForeignKey("LogisticAgentId");

                    b.Navigation("ContainerType");

                    b.Navigation("DivertLane");

                    b.Navigation("LogisticAgent");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.Zebra.ZebraHistorial", b =>
                {
                    b.HasOne("LuxotticaSorting.Core.Container.ContainerTable", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuxotticaSorting.Core.DivertLanes.DivertLane", "DivertLane")
                        .WithMany()
                        .HasForeignKey("DivertLaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuxotticaSorting.Core.Zebra.ZebraConfiguration", "ZebraConfiguration")
                        .WithMany()
                        .HasForeignKey("ZebraConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("DivertLane");

                    b.Navigation("ZebraConfiguration");
                });

            modelBuilder.Entity("LuxotticaSorting.Core.ContainerTypes.ContainerType", b =>
                {
                    b.Navigation("Containers");
                });
#pragma warning restore 612, 618
        }
    }
}
