// <auto-generated />
using System;
using Luxottica.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Luxottica.DataAccess.Migrations
{
    [DbContext(typeof(V10Context))]
    [Migration("20240425162513_AddLastCam")]
    partial class AddLastCam
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Luxottica.Core.Entities.Acknowledgments.Acknowledgment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("ToteLpn")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("WaveNr")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.ToTable("Acknowledgments");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.CameraAssignments.CameraAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<int>("DivertLineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("DivertLineId");

                    b.ToTable("CameraAssignments");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.CameraAssignments.SecondLevel.SecondLevelCamera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.ToTable("SecondLevelCameras");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.Cameras.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.Commissioners.Commissioner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Commissioners");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.DivertLines.DivertLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DivertLineValue")
                        .HasColumnType("int");

                    b.Property<bool>("StatusLine")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DivertLines");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.DivertOutboundLines.DivertOutboundLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CommissionerId")
                        .HasColumnType("int");

                    b.Property<int>("CountMaxTotesLPTUMachine1")
                        .HasColumnType("int");

                    b.Property<int>("CountMaxTotesSPTAMachine1")
                        .HasColumnType("int");

                    b.Property<int>("CountMaxTotesSPTAMachine2")
                        .HasColumnType("int");

                    b.Property<int>("CountMultiTotes")
                        .HasColumnType("int");

                    b.Property<int>("MaxTotesLPTUMachine1")
                        .HasColumnType("int");

                    b.Property<int>("MaxTotesSPTAMachine1")
                        .HasColumnType("int");

                    b.Property<int>("MaxTotesSPTAMachine2")
                        .HasColumnType("int");

                    b.Property<int>("MultiTotes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommissionerId");

                    b.ToTable("DivertOutboundLines");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.HighwayPikingLanes.HighwayPikingLane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CommissionerId")
                        .HasColumnType("int");

                    b.Property<int>("CountMaxTotesLPTUMachine1")
                        .HasColumnType("int");

                    b.Property<int>("CountMaxTotesSPTAMachine1")
                        .HasColumnType("int");

                    b.Property<int>("CountMaxTotesSPTAMachine2")
                        .HasColumnType("int");

                    b.Property<int>("CountMultiTotes")
                        .HasColumnType("int");

                    b.Property<int>("MaxTotesLPTUMachine1")
                        .HasColumnType("int");

                    b.Property<int>("MaxTotesSPTAMachine1")
                        .HasColumnType("int");

                    b.Property<int>("MaxTotesSPTAMachine2")
                        .HasColumnType("int");

                    b.Property<int>("MultiTotes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommissionerId");

                    b.ToTable("HighwayPikingLanes");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.JackpotLines.JackpotLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DivertLineId")
                        .HasColumnType("int");

                    b.Property<bool>("JackpotLineValue")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DivertLineId");

                    b.ToTable("JackpotLines");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.JackpotLines.PickingJackpotLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DivertLineId")
                        .HasColumnType("int");

                    b.Property<bool>("PickingJackpotLineValue")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DivertLineId");

                    b.ToTable("PickingJackpotLines");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.LimitsSettings.LimitSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<int?>("CounterTote")
                        .HasColumnType("int");

                    b.Property<int>("MaximumCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.ToTable("LimitSettingCameras");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.PhysicalMaps.MapPhysicalVirtualSAP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DivertLineId")
                        .HasColumnType("int");

                    b.Property<int>("VirtualSAPZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DivertLineId");

                    b.ToTable("MapPhysicalVirtualSAP");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.Scanlogs.ScanlogsReceivingPicking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CamId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DestinationArea")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("DivertCode")
                        .HasColumnType("int");

                    b.Property<string>("Info")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LapCount")
                        .HasColumnType("int");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<int?>("PutStation")
                        .HasColumnType("int");

                    b.Property<int?>("Release")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusV10")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Timestamp")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int?>("TotalQty")
                        .HasColumnType("int");

                    b.Property<string>("ToteLPN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("TotesInWave")
                        .HasColumnType("int");

                    b.Property<int?>("TrackingId")
                        .HasColumnType("int");

                    b.Property<string>("VirtualTote")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int?>("VirtualZone")
                        .HasColumnType("int");

                    b.Property<string>("Wave")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.ToTable("ScanlogsReceivingPickings");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.ToteHdrs.CountWave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("Nr_Of_Totes_In_Wave")
                        .HasColumnType("int");

                    b.Property<string>("Wave_Nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CountWaves");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.ToteInformations.ToteInformationE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DivTimestamp")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("DivertStatus")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("LastCam")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("LineCount")
                        .HasColumnType("int");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("ToteLPN")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TrackingId")
                        .HasColumnType("int");

                    b.Property<string>("VirtualTote")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("ZoneDivertId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ToteInformations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Luxottica.Core.Entities.CameraAssignments.CameraAssignment", b =>
                {
                    b.HasOne("Luxottica.Core.Entities.Cameras.Camera", "Camera")
                        .WithMany("CameraAssignments")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luxottica.Core.Entities.DivertLines.DivertLine", "DivertLine")
                        .WithMany("CameraAssignments")
                        .HasForeignKey("DivertLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("DivertLine");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.CameraAssignments.SecondLevel.SecondLevelCamera", b =>
                {
                    b.HasOne("Luxottica.Core.Entities.Cameras.Camera", "Camera")
                        .WithMany("SecondLevelCameras")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.DivertOutboundLines.DivertOutboundLine", b =>
                {
                    b.HasOne("Luxottica.Core.Entities.Commissioners.Commissioner", "Commissioner")
                        .WithMany()
                        .HasForeignKey("CommissionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commissioner");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.HighwayPikingLanes.HighwayPikingLane", b =>
                {
                    b.HasOne("Luxottica.Core.Entities.Commissioners.Commissioner", "Commissioner")
                        .WithMany()
                        .HasForeignKey("CommissionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commissioner");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.JackpotLines.JackpotLine", b =>
                {
                    b.HasOne("Luxottica.Core.Entities.DivertLines.DivertLine", "DivertLine")
                        .WithMany("JackpotLines")
                        .HasForeignKey("DivertLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DivertLine");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.JackpotLines.PickingJackpotLine", b =>
                {
                    b.HasOne("Luxottica.Core.Entities.DivertLines.DivertLine", "DivertLine")
                        .WithMany("PickingJackpotLines")
                        .HasForeignKey("DivertLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DivertLine");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.LimitsSettings.LimitSetting", b =>
                {
                    b.HasOne("Luxottica.Core.Entities.Cameras.Camera", "Camera")
                        .WithMany("LimitSettingCameras")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.PhysicalMaps.MapPhysicalVirtualSAP", b =>
                {
                    b.HasOne("Luxottica.Core.Entities.DivertLines.DivertLine", "DivertLine")
                        .WithMany("MapPhysicalVirtualSAPs")
                        .HasForeignKey("DivertLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DivertLine");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Luxottica.Core.Entities.Cameras.Camera", b =>
                {
                    b.Navigation("CameraAssignments");

                    b.Navigation("LimitSettingCameras");

                    b.Navigation("SecondLevelCameras");
                });

            modelBuilder.Entity("Luxottica.Core.Entities.DivertLines.DivertLine", b =>
                {
                    b.Navigation("CameraAssignments");

                    b.Navigation("JackpotLines");

                    b.Navigation("MapPhysicalVirtualSAPs");

                    b.Navigation("PickingJackpotLines");
                });
#pragma warning restore 612, 618
        }
    }
}
